### ISSUE TITLE
Access Models?

### ISSUE THREAD

**Issue by esteban-turnocheck** [jaxon-php/jaxon-codeigniter#1]
How can we access the models from within a JaxonController?
Say, for instance, in the typical case of checking if the email entered in a register form does already exists in a database. How would you go about in the Jaxon class?
I've been looking all over, but examples are very scarce (actually, i've only find one), and does not access the database at all.
I'd thank you much for your help.

**Comment by feuzeu** [comment]
The Jaxon library's goal is to carry the data from the browser to your application, and from your application back to the browser. What the application actually do with the data is out of the scope of the library.
In this specific case, the database access functions are provided by the CodeIgniter framework.

**Comment by feuzeu** [comment]
Hi,
Here's how you can inject your CI models into your Jaxon classes.
You will have to define callbacks, which are documented here: https://www.jaxon-php.org/docs/armada/bootstrap.html.

Add the following controller in your CI app.
```php
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class JaxonRequest extends CI_Controller 
{
    public function __construct()
    {
        parent::__construct();
        // Load the Jaxon library
        $this->load->library('jaxon');
        // Load the session library
        $this->load->library('session'); 
    }

    public function process()
    {
        // Define the Jaxon request processing callbacks.
        $this->jaxon->onInit(function($instance){
            /*
             * Here you can copy any data you need from the CI controller into your Jaxon classes.
             */
            // Insert CI data into the Jaxon class instance
            $instance->load = $this->load; // Now you can call $this->load->... in your Jaxon classes.
            $instance->db = $this->db; // Now you can call $this->db->... in your Jaxon classes.
            $instance->session = $this->session; // Now you can call $this->session->... in your Jaxon classes.

            // This is how you can make you models available in your Jaxon classes
            $this->load('Example_model');
            $instance->Example_model = $this->Example_model;
        });

        // Process the Jaxon request
        if($this->jaxon->canProcessRequest())
        {
            $this->jaxon->processRequest();
        }
    }
}
```

Then set the `core.request.uri` option to the route to the `process()` method.
