### ISSUE TITLE
another CSRF Question

### ISSUE THREAD

**Issue by tom-lp-at** [jaxon-php/jaxon-codeigniter#10]
Dear Feuzeu,
i append to the issue #5 regarding the question of CSRF-Example.
I successful implement the X-CSFR-TOKEN into the Request, but the used Framework (Codeigniter 3) did not use the informations provided in the Header.
It seams to work with "standard" Ajax like so : 
`$.ajax({
    url: 'some_url',
    type: 'POST',
    data: {csrf_test_name: $.cookie('csrf_cookie_name')}
});`
Would it be possible to send the CSRF-Token in jaxon-php as data: too ?
I found the coresponding function in /templates/plugins/config.js.php to inject the token into the Header, but i can´t figure out how i can it append as data: to the request...
Could you give me glue ?
kr Tom
PS: i´am aware that Codeigniter4 has build in the usage of X-CSFR-Token, but the change to the new Framework seams to be heavy for now ;)

**Comment by feuzeu** [comment]
Hi,
You can assign the token to a javascript var, then pass this value to the calls to Jaxon classes. You'll need to also add that parameter to your php functions.

If you are using the Jaxon request factory, you can call `\pm()->js("jsVar")` to add the Js var as parameter to a Jaxon call.

**Comment by tom-lp-at** [comment]
Dear Feuzeu,
thanks for your answer. But the main question is: Where (i assume /jaxon/core/src/Response/Response.php) could i place the injection in PHP-Code, so that the builded JS-Code sends the data in the same "magic Way" that the hole Jaxon-PHP-Library works :) (You are right - i dont like JS-Code and find the Library as a Kind of Life-Saver for People like me) 
kr Tom

**Comment by feuzeu** [comment]
Hi,
It is not a good idea to change the library files, and by the way it is not necessary. There's a couple of ways to achieve what you want to.
You can use a custom header with a a different name, or you can add the token as a parameter to the request url. You'll need in the latest case to set the request url programmatically.

You can then use a request callback https://www.jaxon-php.org/docs/v3x/requests/callbacks.html to handle the token at one single place.
