### ISSUE TITLE
HowTo

### ISSUE THREAD

**Issue by SnowderX2** [jaxon-php/jaxon-codeigniter#11]
Hello,
I am experienced with Jaxon, but I am new into CI.
- I copied the files from app
- But what about files from "src" and where to put the original files from JaxonLibrary?
- Any modifications required as the CI_Controller is named MY_Controller in my project?

Thanks!

**Comment by feuzeu** [comment]
Hi,
Which version of CI are you using? Major changes was introduced in the file structure starting from version 4, thus it is not the same as in the previous versions?
