### ISSUE TITLE
CSRF Example

### ISSUE THREAD

**Issue by musaa32** [jaxon-php/jaxon-codeigniter#5]
can you also implement an example how to use it when csrf is enabled?

**Comment by feuzeu** [comment]
Hi,
Here's the js code to add the csrf token in the Jaxon request header.
```javascript
jaxon.config.postHeaders = {'X-CSRF-TOKEN': csrfToken};
```
For example, you can set the token in a HTML meta tag.
```html
<meta name="csrf-token" content="token-value-here" />
```
And then save it in the Jaxon config using jQuery.
```javascript
$(document).ready(function(){
    if((csrfToken = $('meta[name="csrf-token"]').attr('content')))
    {
        jaxon.config.postHeaders = {'X-CSRF-TOKEN': csrfToken};
    }
});
```

**Comment by feuzeu** [comment]
Hi @musaa32 
Have you tested the above example? Is it what you needed?

**Comment by marlonmarques** [comment]
did not work with this example, always Forbidden

**Comment by musaa32** [comment]
I changed the core to add the csrf token to all posts

**Comment by marlonmarques** [comment]
my config jaxon:

`$config['lib'] = array(
    'core' => array(
        'language' => 'en',
        'encoding' => 'UTF-8',
        'request' => array(
            'uri' => '/jaxon/process',
            'method' => 'POST',
            'csrf_meta' => "csrf-token",`

my config codeigniter
```
$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = 'spos_token';
$config['csrf_cookie_name'] = 'spos_cookie';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = FALSE;
$config['csrf_exclude_uris'] = array();
```

I added meta
`<meta name="csrf-token" content="<?= $this->security->get_csrf_hash() ?>" />`

**Comment by marlonmarques** [comment]
musaa32 as you did?
