### ISSUE TITLE
Register Jaxon user function 

### ISSUE THREAD

**Issue by edrobinson** [jaxon-php/jaxon-codeigniter#7]
I am trying to get Jaxon to work with Codeigniter 3.x using this implementation.
In MY_Controller I write this line:
$this->jaxon->register(Jaxon::USER_FUNCTION, array($this,"dispatch"));
This returns the error:
Argument 1 passed to Jaxon::register() must be of the type array, string given...
The trace leads me to the Armada traits which contains a register method to register the Jaxon classes.
How do I get around this?
Thanks,
Ed

**Comment by feuzeu** [comment]
Hi,

The `register()` method in the Jaxon CI plugin registers the classes you have declared in the config file.
https://www.jaxon-php.org/docs/armada/bootstrap.html
https://www.jaxon-php.org/docs/armada/classes.html
Its only argument is an optional array of additional options.

To register a function, use the `jaxon()` function.
```php
jaxon()->register(Jaxon::USER_FUNCTION, array($this,"dispatch"));
```

**Comment by edrobinson** [comment]
The jaxon() function worked. Thanks.
